version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports: 
      - 9200:9200
    volumes:
      - /home/vianney/data/elasticsearch/lifetrack:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=lifetrack
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx2g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    networks:
    - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
    - 5601:5601
    networks:
    - elastic
    #volumes:
    #  - ./kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  elastic:
    driver: bridge


